### PR TITLE
Grouped bars 2

### LINKED ISSUE #26: Grouped bars

### PR DESCRIPTION
**Pull request by nbedi**
closes #26 

New work in progress:

screen shot 2016-06-09 at 2 05 17 pm

Current implementation works but a bit rough. Figuring out whether there is a better way to handle colors, legends and scales. Let me know if you have any thoughts/suggestions.

### CODE REVIEW

**Comment by nbedi** [comment]
Changes I'm not 100% sure about:
- Changed the ordinal scale to filter domain to unique values. The way it currently handles duplicates is not ideal since it will project values to the first instance of the value but generate a scale according to the count of all values including duplicates. Could also be fixed by changing the calculation of `segments` instead.
- Created a new base class for shapes generated by a `CategorySeries`. This is mostly to handle legends separately but also anything else that may come up. Feels weird creating a separate base class but maybe necessary and more explicit.
- `CategoryShapes` accept sequences as fill color. Need to add support for `style_function` input.
- Added a z axis, scale and type to chart and `CategoryShapes` have a `legend_dimension` property. This is to do a kind of merge between the category dimension and the  'sub-category' dimension (Y in the GroupedBars case, X in GroupedColumns). Category axes and scales replace the axes and scales in the `legend_dimension` and legends are created for the data in the `legend_dimension`.

That last point is probably the funkiest conceptual change I have to think about more.

**Comment by onyxfish** [comment]
I think this is super close. The ordinal stuff itches a little. I'll try to take a closer look this week.

**Comment by nbedi** [comment]
Sounds good, I agree about ordinal stuff, also some color stuff I need to fix up. I'll add some adjustments in the next few days.

**Comment by nbedi** [comment]
Happier with the code now but I'm not sure what to do about the ordinal scale's duplicate value handling.

**Comment by nbedi** [comment]
Added `GroupedColumns` to make sure this set up would actually work well with different shapes/dimensions. It was pretty easy 👍.

**Comment by jpmckinney** [comment]
Closing as stale PR.

**Pull request closed without merging**
